apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: csi-driver
    newName: ghcr.io/scality/playground/anurag4dsb
    newTag: s3-csi-driver-0.0.4
