site_name: "Scality S3 CSI Driver"
site_url: https://scality.github.io/mountpoint-s3-csi-driver
repo_url: https://github.com/scality/mountpoint-s3-csi-driver
edit_uri: edit/documentation/S3CSI-59-delete-obselete-files-add-and-init-documentation/docs/            # ← branch that holds Markdown

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - assets/css/custom.css

plugins:
  - search
  - mermaid2
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - meta
  - toc:
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true
      pygments_style: monokai
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - Home: README.md
  - 'Getting Started':
    - 'Quick Start Guide': quick-start.md
