site_name: "Scality S3 CSI Driver"
site_url: https://scality.github.io/mountpoint-s3-csi-driver
repo_url: https://github.com/scality/mountpoint-s3-csi-driver
edit_uri: edit/main/docs/            # ← branch that holds Markdown

theme:
  logo: assets/images/Scality_logo.png
  favicon: assets/images/Scality_logo.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      accent: teal

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: custom/moon
        name: Switch to dark mode
      accent: teal

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: custom/sun
        name: Switch to system preference
      accent: teal
  custom_dir: docs/assets/
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - toc.follow

extra_css:
  - assets/css/custom.css

extra:
  generator: false

plugins:
  - search
  - mermaid2
  - awesome-pages

markdown_extensions:
  - admonition # Enables notes, warnings, etc. Usage: !!! note
  - pymdownx.details  # For collapsible sections. Usage: ::: details
  - tables # For tables. Usage: |
  - attr_list  # For adding attributes to markdown elements (e.g., for badges). Usage: [!badge text](url)
  - md_in_html # For markdown in HTML. Usage: <div markdown="1">
  - meta # For metadata. Usage: --- title: "My Page" author: "John Doe" date: 2021-01-01 ---
  - toc:
      permalink: '#' # Adds anchor links to headings. Usage: [Heading](#heading)
      toc_depth: 2    # Depth of headings to include in the table of contents
      title: "On This Page"
  - pymdownx.highlight:
      line_spans: __span         # Enables line highlighting and selection
      pygments_lang_class: true  # Adds language class for better styling
      linenums: true             # Shows line numbers on code blocks
      pygments_style: monokai    # Style of code blocks
  - pymdownx.inlinehilite       # Enables inline code highlighting
  - pymdownx.snippets           # Enables code snippets inclusion
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_div_format

copyright: |
  Copyright &copy; 2025 Scality, Inc. All rights reserved. |
  <a href="https://github.com/scality/mountpoint-s3-csi-driver/blob/main/LICENSE">Apache License 2.0</a>

nav:
  - Home: README.md
  - Driver Deployment:
      - Prerequisites: driver-deployment/prerequisites.md
      - Quick Start: driver-deployment/quick-start.md
      - Detailed Installation: driver-deployment/detailed-installation.md
      - Uninstallation: driver-deployment/uninstallation.md
  - Volume Provisioning:
      - How-To Guides:
          - Overview: volume-provisioning/how-to/index.md
          - Override Region: volume-provisioning/how-to/override-region.md
      - Prerequisites: volume-provisioning/prerequisites.md
  - Concepts and Reference:
      - Helm Chart Configuration Reference: concepts-and-reference/helm-chart-configuration-reference.md
      - Permissions: concepts-and-reference/permissions.md
  - Configuration:
      - Overview: configuration/index.md
      - Volume Configuration: configuration/volume-configuration.md
      - Mount Options: configuration/mount-options.md
  - How-To Guides:
      - Static Provisioning: how-to/static-provisioning.md
      - Mount Multiple Buckets: how-to/multi-volume.md
      - Region Override: how-to/region-override.md
      - Permissions & Non-Root Access: how-to/permissions.md
  - Concepts:
      - Filesystem Semantics: concepts/filesystem-semantics.md
  - Reference:
      - Compatibility Matrix: reference/compatibility-matrix.md
  - Operations:
      - Troubleshooting: troubleshooting.md
      - Administrator and User Guide: admin-user-guide.md
  - Reference:
      - Minimal Helm Example: examples/minimal-helm.yaml
