name: "CI Setup"
description: "Shared CI setup: registry login, Helm, Mage, Kind cluster"
inputs:
  cluster_name:
    description: "Name for the Kind cluster"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io/scality
        username: "${{ github.repository_owner }}"
        password: "${{ github.token }}"

    - name: Setup Helm
      uses: azure/setup-helm@v4.3.1

    - name: Install Mage
      shell: bash
      run: |
        go install github.com/magefile/mage@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Create Kind Cluster
      uses: helm/kind-action@v1.12.0
      with:
        wait: 90s
        cluster_name: ${{ inputs.cluster_name }}
