apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: csi-driver
    newName: ghcr.io/scality/mountpoint-s3-csi-driver
    newTag: local2
# configMapGenerator:
#   - name: s3-csi-driver-config
#     behavior: merge
#     literals:
#       - endpoint-url=http://192.168.1.42:8000