apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-region-override-pv
spec:
  capacity:
    storage: 1200Gi # Arbitrary value - not used for S3
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    namespace: default
    name: s3-region-override-pvc
  mountOptions:
    - allow-delete
    - region=eu-west-1  # Override S3 region for this specific volume
  csi:
    driver: s3.csi.scality.com
    volumeHandle: s3-csi-region-override-volume # Must be unique across all PVs
    volumeAttributes:
      bucketName: my-eu-west-bucket
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-region-override-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi # Ignored but required
  volumeName: s3-region-override-pv # Must match PV `metadata.name`
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-region-app
spec:
  containers:
    - name: app
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", "echo 'Data from EU West region!' >> /data/$(date -u).txt; tail -f /dev/null"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: s3-region-override-pvc
