name: CI Build and Unit Tests

on:
  push:
    branches:
      - '**'

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Check style
      run: make check_style

    - name: Install Go Test Coverage
      run: make install-go-test-coverage

    - name: Build
      run: make bin

    - name: Test
      # Run tests as root as we require it for systemd tests
      run: sudo make test

    - name: Check test coverage
      run: make cover

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: scality/mountpoint-s3-csi-driver

  dev-image:
    name: Dev Image
    permissions:
      contents: read
      packages: write
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    with:
      context: .
      name: mountpoint-s3-csi-driver
      namespace: ${{ github.repository_owner }}
      tag: ${{ github.sha }}
