name: CI & E2E Tests

on:
  push:
    branches:
      - '**'

jobs:
  dev-image:
    name: Dev Image
    permissions:
      contents: read
      packages: write
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    with:
      context: .
      name: mountpoint-s3-csi-driver
      namespace: ${{ github.repository_owner }}
      tag: ${{ github.sha }}

  controller-e2e-tests:
    name: E2E Controller Tests
    runs-on: ubuntu-22.04
    needs: dev-image
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Common Setup
        uses: ./.github/actions/e2e-setup-common
        with:
          ref: ${{ github.sha }}

      - name: Run Controller Tests
        run: make e2e-controller

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./e2e-controller-tests-results.xml
          flags: e2e_controller_tests
          slug: scality/mountpoint-s3-csi-driver

  scality-e2e-tests:
    name: Scality E2E Tests
    runs-on: ubuntu-22.04
    needs: dev-image
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Common Setup
        uses: ./.github/actions/e2e-setup-common
        with:
          ref: ${{ github.sha }}

      - name: Get Host IP Address
        id: get_ip
        run: echo "host_ip=$(hostname -I | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Run Scality Tests
        run: |
          mkdir -p test-results
          make e2e-scality-all \
            S3_ENDPOINT_URL=http://${{ steps.get_ip.outputs.host_ip }}:8000 \
            ACCESS_KEY_ID=accessKey1 \
            SECRET_ACCESS_KEY=verySecretKey1 \
            CSI_IMAGE_TAG=${{ github.sha }} \
            CSI_IMAGE_REPOSITORY=ghcr.io/${{ github.repository }} \
            ADDITIONAL_ARGS="--junit-report=./test-results/scality-e2e-tests-results.xml"
        
      - name: Copy test results to expected location
        if: ${{ !cancelled() }}
        run: |
          # Make sure the directory exists
          mkdir -p ./test-results/
          # Copy from the actual location to the expected location
          find ./tests/e2e-scality/e2e-tests -name "scality-e2e-tests-results.xml" -exec cp {} ./test-results/ \;
          # Also check for any XML files that might have been created
          find ./tests/e2e-scality/e2e-tests -name "*.xml" -exec cp {} ./test-results/ \;
          # List files to verify
          echo "Files found in e2e-tests directory:"
          find ./tests/e2e-scality/e2e-tests -name "*.xml"
          echo "Files in test-results directory:"
          ls -la ./test-results/ || true
        
      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: scality-e2e-test-results
          path: |
            ./logs/
            ./tests/e2e-scality/e2e-tests/*.log
            ./tests/e2e-scality/e2e-tests/**/*.xml
            ./test-results/
          if-no-files-found: warn
          
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./test-results/scality-e2e-tests-results.xml
          flags: scality_e2e_tests
          slug: scality/mountpoint-s3-csi-driver
