name: CI & E2E Tests

on:
  push:
    branches:
      - '**'

env:
  IMAGE_NAME: "mountpoint-s3-csi-driver"
  REGISTRY: "ghcr.io/scality"
  TAG: "${{ github.sha }}"
  PLATFORM: "linux/amd64"
  KUBECONFIG: /home/runner/.kube/config

jobs:
  dev-image:
    name: Dev Image
    permissions:
      contents: read
      packages: write
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    with:
      context: .
      name: mountpoint-s3-csi-driver
      namespace: ${{ github.repository_owner }}
      tag: ${{ github.sha }}

  controller-e2e-tests:
    name: E2E Controller Tests
    runs-on: ubuntu-22.04
    needs: dev-image
    steps:
      - name: Run Common Setup
        uses: ./.github/actions/setup-common
        with:
          ref: ${{ github.sha }}
      - name: Run Controller Tests
        run: make e2e-controller