name: CI E2E Controller tests

on:
  workflow_run:
    workflows: ["Build Development Image"] # <- Must match exactly the 'name' of the dev-image-build.yml
    types:
      - completed
    branches:
      - '**'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
      debug_delay_duration_minutes:
        type: number
        description: 'Duration to delay job completion in minutes'
        required: false
        default: 5

env:
  IMAGE_NAME: "mountpoint-s3-csi-driver"
  REGISTRY: "ghcr.io/scality"
  TAG: "${{ github.sha }}"
  PLATFORM: "linux/amd64"

jobs:
  e2e-tests-with-helm:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Run E2E Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ github.token }}"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Install Ginkgo CLI
        run: go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.12.0
        with:
          version: v0.21.0
          wait: 90s
          cluster_name: helm-test-cluster

      - name: Pull Dev Image into KIND Cluster
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha || github.sha }}
          kind load docker-image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha || github.sha }} --name helm-test-cluster

      - name: Run Controller Tests
        run: make e2e-controller