name: Release
run-name: release ${{ github.event.inputs.tag }}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to be released (e.g., 1.0.0)"
        required: true
      all_platforms:
        description: "Build for all platforms (linux/amd64,linux/arm64) or just linux/amd64"
        required: false
        type: boolean
        default: false

jobs:
  prod-container-with-docker:
    permissions:
      contents: read
      packages: write
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    with:
      context: .
      name: mountpoint-s3-csi-driver
      namespace: ${{ github.repository_owner }}
      tag: ${{ inputs.tag }}
      platforms: ${{ inputs.all_platforms && 'linux/amd64,linux/arm64' || 'linux/amd64' }}

  package-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.16.2

      - name: login to ghcr.io with helm
        run: helm registry login -u actions -p ${{ github.token }} ghcr.io

      - name: Package Helm Chart
        run: |
          helm package ./charts/scality-mountpoint-s3-csi-driver --version ${{ inputs.tag }} --app-version ${{ inputs.tag }}

      - name: Upload Helm Chart as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: scality-mountpoint-s3-csi-driver-${{ inputs.tag }}.tgz

      - name: Push helm chart to ghcr.io
        run: helm push scality-mountpoint-s3-csi-driver-${{ inputs.tag }}.tgz oci://ghcr.io/${{ github.repository }}/helm-charts

      - name: Pull the helm chart
        run: helm pull oci://ghcr.io/${{ github.repository }}/helm-charts/scality-mountpoint-s3-csi-driver --version ${{ inputs.tag }}

      - name: Show the helm chart
        run: helm show all oci://ghcr.io/${{ github.repository }}/helm-charts/scality-mountpoint-s3-csi-driver --version ${{ inputs.tag }}

      - name: Template the helm chart
        run: helm template oci://ghcr.io/${{ github.repository }}/helm-charts/scality-mountpoint-s3-csi-driver --version ${{ inputs.tag }}

  create-github-release:
    runs-on: ubuntu-latest
    needs: [prod-container-with-docker, package-helm-chart]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download Helm Chart Artifact
        uses: actions/download-artifact@v4
        with:
          name: helm-chart
          path: ./release-assets

      - name: Generate checksums
        run: |
          cd ./release-assets
          sha256sum scality-mountpoint-s3-csi-driver-${{ inputs.tag }}.tgz > scality-mountpoint-s3-csi-driver-${{ inputs.tag }}.tgz.sha256

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ github.sha }}
          tag_name: ${{ inputs.tag }}
          name: Release ${{ inputs.tag }}
          generate_release_notes: true
          files: |
            ./release-assets/scality-mountpoint-s3-csi-driver-${{ inputs.tag }}.tgz
            ./release-assets/scality-mountpoint-s3-csi-driver-${{ inputs.tag }}.tgz.sha256
          body: |
            ## Scality S3 CSI Driver

            📚 **Documentation**: https://scality.github.io/mountpoint-s3-csi-driver/

            ### 📦 Release Assets
            - **Helm Chart**: `scality-mountpoint-s3-csi-driver-${{ inputs.tag }}.tgz` (attached below)
            - **Docker Image**: `ghcr.io/scality/mountpoint-s3-csi-driver:${{ inputs.tag }}` (multi-arch: linux/amd64, linux/arm64)
            - **Helm OCI**: `oci://ghcr.io/scality/mountpoint-s3-csi-driver/helm-charts/scality-mountpoint-s3-csi-driver:${{ inputs.tag }}`

            ### 🔍 What's Changed
            <!-- GitHub will auto-populate this section with commits and PRs -->
